// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-XXYmP1R30hs72Vdk9j0Hf_MOp1PBtM',
    appId: '1:444538853268:web:1884e7ea23436a46e0e181',
    messagingSenderId: '444538853268',
    projectId: 'mobileapp-fd843',
    authDomain: 'mobileapp-fd843.firebaseapp.com',
    storageBucket: 'mobileapp-fd843.firebasestorage.app',
    measurementId: 'G-PV605J01S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNeCQOTt551P6SWNrRVaKUNqSpN51-KE',
    appId: '1:444538853268:android:24e363b636cb81ade0e181',
    messagingSenderId: '444538853268',
    projectId: 'mobileapp-fd843',
    storageBucket: 'mobileapp-fd843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrWRPEXXZvpnmEIx3LLxBUpyeOH0aGjo',
    appId: '1:444538853268:ios:0534fbd086c5e6ece0e181',
    messagingSenderId: '444538853268',
    projectId: 'mobileapp-fd843',
    storageBucket: 'mobileapp-fd843.firebasestorage.app',
    iosClientId: '444538853268-4ggb16bf2r18s8g1usqk37un6cjko16g.apps.googleusercontent.com',
    iosBundleId: 'com.example.printSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrWRPEXXZvpnmEIx3LLxBUpyeOH0aGjo',
    appId: '1:444538853268:ios:0534fbd086c5e6ece0e181',
    messagingSenderId: '444538853268',
    projectId: 'mobileapp-fd843',
    storageBucket: 'mobileapp-fd843.firebasestorage.app',
    iosClientId: '444538853268-4ggb16bf2r18s8g1usqk37un6cjko16g.apps.googleusercontent.com',
    iosBundleId: 'com.example.printSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ-XXYmP1R30hs72Vdk9j0Hf_MOp1PBtM',
    appId: '1:444538853268:web:1a1182a4375bab7de0e181',
    messagingSenderId: '444538853268',
    projectId: 'mobileapp-fd843',
    authDomain: 'mobileapp-fd843.firebaseapp.com',
    storageBucket: 'mobileapp-fd843.firebasestorage.app',
    measurementId: 'G-E9VLNLN482',
  );
}
